name: CI

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2

      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Format
        run: cargo fmt --all -- --check

  test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2

      - name: Run Tests
        run: cargo test --all

  audit:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Run cargo-audit
        run: cargo audit

  spellcheck:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install ripgrep spellcheck

      - name: Check for Forbidden Words
        run: spellcheck --forbidden-words-file forbidden_words.txt --ignore-words-file allowed_words.txt --ignore-case --ignore-numbers --ignore-urls --ignore-emails --ignore-strings '.*' .

      - name: Check for TODOs
        run: rg --type-add 'todo:ext:rs' -t rs -e 'TODO|FIXME' .

  docs:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2

      - name: Build Documentation
        run: cargo doc --no-deps

      - name: Upload Documentation Artifact
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: target/doc

  benchmarks:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2

      - name: Run Benchmarks
        run: cargo bench
