name: CI

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2

      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Format
        run: cargo fmt --all -- --check

  test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2

      - name: Run Tests
        run: cargo test --all -- --test-threads=1 | tee test-report.json

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: ./test-report.json

  audit:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Run cargo-audit
        run: cargo audit

  deny:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2

      - name: Install cargo-deny
        run: cargo install cargo-deny

      - name: Run cargo-deny check
        run: cargo deny check

  tarpaulin:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2

      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Run Coverage (LCOV)
        run: cargo tarpaulin --out Lcov

      - name: Upload Coverage (LCOV)
        uses: actions/upload-artifact@v4
        with:
          name: lcov-report
          path: ./lcov.info

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    needs: [lint, tarpaulin, test]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Coverage Report
        uses: actions/download-artifact@v4
        with:
          name: lcov-report
          path: ./lcov.info

      - name: Download Test Report
        uses: actions/download-artifact@v4
        with:
          name: test-report
          path: ./test-report.json

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.coverageReportPaths=lcov.info
            -Dsonar.testExecutionReportPaths=./test-report.json

  codecov:
    runs-on: ubuntu-latest
    needs: tarpaulin

    steps:
      - uses: actions/checkout@v4

      - name: Download LCOV Report
        uses: actions/download-artifact@v4
        with:
          name: lcov-report
          path: ./lcov.info

      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}

  benchmarks:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2

      - name: Run Benchmarks
        run: cargo bench
